# Define your activity categories and their mappings
macro_activities_mapping:
  CATEGORY_1:
    macro_variants:
      - "CAT1"
      - "CATEGORY1"
      - "CATEGORY ONE"
    micro_keywords:
      - "keyword1"
      - "keyword2"
      - "specific phrase"

  CATEGORY_2:
    macro_variants:
      - "CAT2"
      - "CATEGORY2"
    micro_keywords:
      - "another keyword"
      - "specific term"

  OTHER:  # Always include an OTHER category
    macro_variants:
      - "OTHER"
      - "MISC"
      - "MISCELLANEOUS"
    micro_keywords:
      - "miscellaneous"
      - "various"
      - "other activities"

# Events to exclude from analysis
excluded_events:
  - "OOF"
  - "OUT OF OFFICE"
  - "VACATION"
  - "HOLIDAY"

# Colors for visualization (hex codes)
macro_colors:
  CATEGORY_1: '#4287f5'
  CATEGORY_2: '#f54242'
  OTHER: '#808080'