# Holidays and vacations configuration
# Format: YYYY-MM-DD for all dates

holidays:
  2023:
    - "2023-01-01"  # New Year's Day
    - "2023-04-10"  # Easter Monday
    - "2023-04-25"  # Liberation Day
    - "2023-05-01"  # Labor Day
    - "2023-06-02"  # Republic Day
    - "2023-08-15"  # Assumption Day
    - "2023-11-01"  # All Saints' Day
    - "2023-12-25"  # Christmas Day
    - "2023-12-26"  # St. Stephen's Day
  
  2024:
    - "2024-01-01"  # New Year's Day
    - "2024-04-01"  # Easter Monday
    - "2024-04-25"  # Liberation Day
    - "2024-05-01"  # Labor Day
    - "2024-06-02"  # Republic Day
    - "2024-08-15"  # Assumption Day
    - "2024-11-01"  # All Saints' Day
    - "2024-12-25"  # Christmas Day
    - "2024-12-26"  # St. Stephen's Day

  2025:
    - "2025-01-01"  # New Year's Day
    - "2025-04-21"  # Easter Monday
    - "2025-04-25"  # Liberation Day
    - "2025-05-01"  # Labor Day
    - "2025-06-02"  # Republic Day
    - "2025-08-15"  # Assumption Day
    - "2025-11-01"  # All Saints' Day
    - "2025-12-25"  # Christmas Day
    - "2025-12-26"  # St. Stephen's Day

vacations:
  2023:
    - start: "2023-08-01"
      end: "2023-08-15"
      description: "Summer Vacation"
    - start: "2023-12-23"
      end: "2023-12-31"
      description: "Winter Break"
  
  2024:
    - start: "2024-08-01"
      end: "2024-08-15"
      description: "Summer Vacation"
    - start: "2024-12-23"
      end: "2024-12-31"
      description: "Winter Break"
  
  2025:
    - start: "2025-08-01"
      end: "2025-08-15"
      description: "Summer Vacation"
    - start: "2025-12-23"
      end: "2025-12-31"
      description: "Winter Break"