# Default period settings for fiscal quarters and years
default_periods:
  quarter:
    start_month: 1  # January
    duration_months: 3
  year:
    start_month: 1  # January
    end_month: 12   # December

# Active time range for analysis
# Format: YYYY-MM-DD
active_range:
  start_date: "2025-01-01"
  end_date: "2025-12-31"

# Daily view range (for daily hours visualization)
# Format: YYYY-MM-DD
daily_view_range:
  start_date: "2025-01-01"
  end_date: "2025-01-31"  # Default to show one month